artifact_location: file:///Users/mac/Documents/PythonProjects/Months 3/mlflow_runs/298425548643314000
creation_time: 1777703563900
experiment_id: '298425548643314000'
last_update_time: 1777703563900
lifecycle_stage: active
name: Months3_Experiment
trace_location: null
workspace: default
