artifact_location: file:///Users/mac/Documents/PythonProjects/Months 3/mlflow_runs/867642882096534210
creation_time: 1777403065766
experiment_id: '867642882096534210'
last_update_time: 1777403065766
lifecycle_stage: active
name: Months3_Experiment
trace_location: null
workspace: default
