name: ML CI Pipeline

on: [push]

jobs:
  run-ml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ML script
        run: python hello.py

      - name: Check output file
        run: |
          if [ ! -f models/model.pkl ]; then
            echo "Model not created!"
            exit 1
          fi
      - name: Build Docker image
        run: docker build -t myapp .